@host=localhost:8787

### 
GET http://{{host}}/posts
content-type: application/json

### 
GET http://{{host}}/posts/123
content-type: application/json

### 
POST http://{{host}}/posts
content-type: application/json

{
    "title": "title",    
    "body": "body 1"    
}

### 
PATCH http://{{host}}/posts/123
content-type: application/json

{
    "name": "country"    
}

### 
DELETE http://{{host}}/posts/123
content-type: application/json